"""empty message

Revision ID: 806574100eaf
Revises: 6070c0584130
Create Date: 2025-12-29 20:25:43.563435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806574100eaf'
down_revision = '6070c0584130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
